INSERT INTO TAB_PESSOA (TP_NOME, TP_IDADE, TP_PESO, TP_GRUPO) VALUES ('Anderson', 23, 56.8, 'Adulto');
INSERT INTO TAB_PESSOA (TP_NOME, TP_IDADE, TP_PESO, TP_GRUPO) VALUES ('Matheus', 12, 46, 'Criança');
INSERT INTO TAB_PESSOA (TP_NOME, TP_IDADE, TP_PESO, TP_GRUPO) VALUES ('Jonas', 46, 74.2, 'Adulto');
INSERT INTO TAB_PESSOA (TP_NOME, TP_IDADE, TP_PESO, TP_GRUPO) VALUES ('Raimundo', 67, 74.2, 'Idoso');